### ISSUE TITLE
Edit: Very dark bushes in the game (DirectX 8 & 9)

### ISSUE THREAD

**Issue by Skajdrowski** [crosire/d3d8to9#105]
I want simple answer, yes or no. If yes, could you make that for us ? I wanna know what will happen if I'll run DX 8 game on DX 10 resources :)

**Comment by elishacloud** [comment]
Yes, it is possible, but the architecture changed after DirectX 9 so converting from DirectX 8 to other versions of DirectX usually requires adding some type of emulation layer.  Whereas d3d8to9 is just is a straight conversion from DirectX 8 to DirectX 9.  This means d3d8to9 should be faster and more compatible than converting to a higher version of DirectX.

Also most tools, like [ReShade](https://reshade.me/) support starting with DirectX9 or newer.  So getting the game up to at least DirectX9 opens up a world of tools that don't exist with DirectX 8.

Plus, there are already tools out there that convert the game to newer versions:
* [dgVoodoo2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html) - This converts from DirectX 8 to DirectX 11.
* [dxvk](https://github.com/doitsujin/dxvk) - They _just_ added a DirectX 9 conversion to Vulkan.  So you can use d3d8to9 to convert the game to DirectX 9 and then dxvk to convert the game to Vulkan.  I tested several games myself and it works pretty good.

**Comment by Skajdrowski** [comment]
So I just need to drag all of the required dlls to a game like with d3d8tod3d9 ?

**Comment by elishacloud** [comment]
From the logs it looks like the game is using surface format `D3DFMT_W11V11U10`.   It looks like dxvk does not support the format, and maybe your computer does not support the format either.  Without looking into this at all, my guess is that the trees use this format and since the format is not supported, they just show up as black.  Most likely we would need to build emulation for that format, but I don't think we plan to do that in this project.

The issue may be similar to this issue specified [here](https://github.com/elishacloud/dxwrapper/issues/52).

_Note: this format appears to be specific to DirectX 8, or at least it is not supported in DirectX 9._

**Comment by Skajdrowski** [comment]
I don't really know what's going on in that linked thread. I really don't like when something is being broken so I'm trying to fix that without knowledge. Is there any fix to that render bug ? I don't want to dual-boot windows xp specially for few old games :(

**Comment by elishacloud** [comment]
What game are you trying to get working on Windows 10?  If I can get a copy of the game I can try and look into this when I get a chance.

You could also try [dgVoodoo2](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html).  It might be using emulation to support this format.

**Comment by Skajdrowski** [comment]
The game I'm running is called ,,Sniper Elite Berlin 1945"
Here is a steam page: https://store.steampowered.com/app/3700/Sniper_Elite/?l=english

**Comment by Skajdrowski** [comment]
@elishacloud Still no way to get it fixed ? I can provide you my GoG installator if you want

**Comment by elishacloud** [comment]
Thanks!  I already own this game, but I have never played it.  Based on [this](https://narkive.com/jea24FdU:4.1223.44) comment from a lead developer at Microsoft on the DirectX team, format `D3DFMT_W11V11U10` has been dropped on DirectX 9.  This is the issue here.

I think I can use another texture format and then convert the data, but I have not had much time to look into this.  Can you tell me how to reproduce the issue?

**Comment by Skajdrowski** [comment]
@elishacloud Oh I forgot that this thread still exists :D

The issue just occurs on newer Windows versions (7, 8.1 & 10) I guess

This game natively supports DirectX 8 but the bushes still remained Dark, I tried putting d3d8to9 into the game and even emulate newer DirectX versions and it still didn't had fixed these bushes.

**Comment by Skajdrowski** [comment]
Apparently, this glitch doesn't happen on GOG version of the game.
