### ISSUE TITLE
Use D3D9 private data instead of AddressLookupTable

### ISSUE THREAD

**Issue by CookiePLMonster** [crosire/d3d8to9#125]
This is more of a meta-issue to brainstorm an idea, so I hope it's okay:

Right now d3d8to9 uses `AddressLookupTable` to store reverse lookup tables from D3D9 resources to wrapped D3D8 resources. Perhaps stashing D3D8 pointers inside D3D9's resource private data is better? If I understand the problem correctly, it'd help avoid having to maintain this lookup table and instead let the resources themselves hold this data.

**Comment by crosire** [comment]
Souds like a good idea. Only issue I'm seeing is that `IDirect3DSwapChain9` does not have private data. Looks like the address cache is only used for `QueryInterface` there though, so is probably not necessary and can be implemented without.

**Comment by CookiePLMonster** [comment]
Same about `IDirect3D9` and `IDirect3DDevice9`, which I think are in the cache too - but worst case, the lookup cache could be kept only for those and not the other resources.

**Comment by elishacloud** [comment]
Interesting idea.  We used to [delete each interface](https://github.com/crosire/d3d8to9/blob/8b8738335304427049121734e42997043064c27b/source/d3d8to9_surface.cpp#L48-L51) once the interface was released.  However, the main reason we added caching was because some games would release an interface (in this case the surface) but still try to access the released interface.  See #21.

Direct3D8 and Direct3D9 allows accessing released interfaces and only clears them out once the root device is released. Our solution was to create a caching table and then [delete all the interfaces](https://github.com/crosire/d3d8to9/blob/359d5d00eeb5d8795d1297948889333377a77173/source/interface_query.cpp#L9-L14) only after the root device was released.

If we store the addresses in a D3D9 resources, how will we be able to delete the interfaces once the root D3D9 device is released?

**Comment by CookiePLMonster** [comment]
Ouch, I wasn't aware that **this** is the reason, in which case the lookup table is probably okay - alternately, both could be used in conjunction so the lookup table becomes only a 'deleter'.

**Comment by elishacloud** [comment]
BTW: there is a new [Discussions](https://dzhavat.github.io/2020/04/04/my-thoughts-on-github-discussions.html) feature that GitHub added that can be [enabled](https://github.com/elishacloud/dxwrapper/discussions).  It is for the topics like this.

**Comment by elishacloud** [comment]
There may be a way that we can get D3D9 to trigger us when the interface is released.  If we use the [`D3DSPD_IUNKNOWN`](https://docs.microsoft.com/en-us/windows/win32/api/d3d9helper/nf-d3d9helper-idirect3dresource9-setprivatedata) flag than:

> The data at pData is a pointer to an IUnknown interface. SizeOfData must be set to the size of a pointer to IUnknown, that is, sizeof(IUnknown*). **Direct3D automatically callsIUnknown through pData when the private data is destroyed.** Private data will be destroyed by a subsequent call to IDirect3DResource9::SetPrivateData with the same GUID, a subsequent call to IDirect3DResource9::FreePrivateData, or when the IDirect3D9 object is released. For more information, see Remarks.

We could then put the released interface on a list to be deleted once the root device is removed.

**Comment by CookiePLMonster** [comment]
> We could then put the released interface on a list to be deleted once the root device is removed.

Sounds good to me! It's only a matter of passing something like an `InterfaceDeleter` (which implements `IUnknown` only) with a resource as a parameter, something like:

```cpp
IUnknown* deleter = new InterfaceDeleter(this); // any IDirect3DResource9
m_proxy->SetPrivateData(....);
```

**Comment by elishacloud** [comment]
Note that only surfaces, textures and buffers support resources.  So only these interfaces can store the D3D8 pointers.  But this may be ok because I don't think we ever use the lookup table for the other interfaces.  Also, I suspect that the other interfaces actually get deleted by D3D9 when they are released. If we do this, we may be able to remove the `AddressLookupTable` all together.  But it would need to be tested.

This also means that we would be relying on the D3D9 resources feature and if this feature is ever broken it could break us.  It may also impact other projects, like the [dxvk](https://github.com/doitsujin/dxvk) project that converts D3D9 to vulkan.  In cases like this if the resource feature works differently than in the actual D3D9 implementation it may break us.

**Comment by CookiePLMonster** [comment]
It's been long agreed that this was not a good suggestion.
