### ISSUE TITLE
Consider recommending D3DX from NuGet instead of an old DirectX SDK

### ISSUE THREAD

**Issue by CookiePLMonster** [crosire/d3d8to9#149]
"Modern" D3DX with signed libraries can nowadays be found on NuGet and vcpkg, as described [HERE](https://walbourn.github.io/legacy-d3dx-on-nuget/) This has a few benefits:
1. DirectX SDK is obviously deprecated, it's also quite a big package and usually only this one DLL is needed.
2. The DLL is SHA-2 signed, unlike the SDK one.
3. There is no need for Admin access to install it, since that DLL is supposed to land on the application directory.
4. The project could likely stop depending on DXSDK entirely by using the NuGet package + Windows SDK instead - simplifying compilation instructions.

I've successfully used that approach in [World Racing 2 CE](https://store.steampowered.com/app/1301010/World_Racing_2__Champion_Edition/) and it works equally good to relying on an old SDK.

**Comment by crosire** [comment]
Building d3d8to9 doesn't require the old DX SDK, all the necessary declarations are local in https://github.com/crosire/d3d8to9/blob/main/source/d3dx9.hpp. That's needed to make it possible to build this project with just CMake (with toolchains that do not have Nuget).
So the only requirement is the `d3dx9_43.dll` at runtime (+ `d3dcompiler_43.dll` through that). It doesn't really matter to d3d8to9 where that comes from, whether installed through the old DX runtime or by extracting it from the D3DX Nuget package. But I would argue that it's easier for a user to click on a download link for the DX runtime installer, rather than having to go through finding and downloading the Nuget package and extracting its contents (for us that's easy, but same cannot be said about all users).

**Comment by CookiePLMonster** [comment]
This is true, but at the very least it's still worth a mention.

**Comment by SwiftyOne1** [comment]
will this work with Nascar 2003 season?
