### ISSUE TITLE
[Suggestion] The Bard's Tale (2005) - Solve the slowness of some parts...

### ISSUE THREAD

**Issue by SilentMRG** [crosire/d3d8to9#165]
Hello...

I was having a complete slowdown and I used your dll, and the slowdown was gone... Now it only occurs when I walk under treetops and in some areas with puddles of water. So I wanted to propose a fix for this: Please, maybe unlocking the fps to something higher than 60 would help, I think the game is stuck at 30fps. Anyway, I also think that the 2005 version uses DirectX 8, which is why your fix worked so well removing much of the slowness. Well, I don't know if my suggestion is possible, hehe.

Thank you very much for your attention!

**Comment by elishacloud** [comment]
I don't think there is any plans on this project to make options like that.  This tool just converts the game as is to Direct3D9.  If you want to add other features you can use my [dxwrapper](https://github.com/elishacloud/dxwrapper) tool.  That will allow you to force v-sync off, if that is the issue.

If the issue is not v-sync then it could be hard coded into the game.  That would require changes to the game binary, which is outside the scope of either of these projects.
