### ISSUE TITLE
FPS issue ? Warcraft III

### ISSUE THREAD

**Issue by Karaulov** [crosire/d3d8to9#50]
Without d3d8to9 FPS always 64, after install d3d8to9 FPS slow down to 40.

Windows 7 x64
Compiled with Visual Studio 2017 - Windows XP (v141_xp) with default compiler settings.

**Comment by Karaulov** [comment]
WIth ENB dx8 to dx9 converter ( http://enbdev.com/download_convertor_dx8todx9.htm ) have same problem. (FPS slower that in d3d8)

**Comment by elishacloud** [comment]
Interesting.  My version of Warcraft III already uses Direct3D9 so d3d8to9 is not needed.  I am running the Reign of Chaos with the Frozen Throne expansion version 1.27.0.52240.

What version of Warcraft III are you using?

**Comment by Karaulov** [comment]
1.27 version with bugs (random crashes, broken orders, etc) i use 1.26a

VIDEO 9500GT
CPU AMD 4400+ 2x core
Windows 7 x64

With default d3d8 i got 64FPS , after install d3d8to9 i got ~50FPS.

**Comment by Karaulov** [comment]
1.26a with d3d8: FPS 64.0

![1.26a with d3d8: FPS 64.0](https://user-images.githubusercontent.com/6445336/30729134-e42a46d0-9f65-11e7-9b59-5d1ce528d076.jpg)

1.26a with d3d8to9: FPS slow down to 30

![1.26a with d3d8to9: FPS slow down to 30](https://user-images.githubusercontent.com/6445336/30729145-fe1a6b9c-9f65-11e7-98a6-4d46b91e5c18.jpg)

1.27a with d3d9 : FPS 27

![1.27a with d3d9 : FPS 27](https://user-images.githubusercontent.com/6445336/30729179-59680946-9f66-11e7-9cd1-e4cf304fe5e4.jpg)

**Comment by Karaulov** [comment]
[d3d8_hook_log.txt](https://github.com/crosire/d3d8to9/files/1323431/d3d8_hook_log.txt)

**Comment by Karaulov** [comment]
127b version with d3d9 64 FPS!!  But this version replaced by new, all users use 126a(PvPGN old version) or 128c+(Battle.net latest version) 

![me5vniu 1](https://user-images.githubusercontent.com/6445336/30729948-f7fd5b10-9f6b-11e7-944c-3233c3a02058.jpg)

why ?

**Comment by Karaulov** [comment]
With this d3d8 to 9 converter: https://www.hiveworkshop.com/threads/warcraft-3-in-windows-10-os.269225/
FPS always 64 as with d3d8.

**Comment by Karaulov** [comment]
In fullscreen:
1.26a (d3d8) : 64.0 FPS 
1.26a + d3d8to9: 40 FPS 
1.27a (d3d9) : 40 FPS 

In window (smaller than screen) fps 64

**Comment by Keith94** [comment]
@Karaulov Off topic, but the FPS cap can also be removed, correct? It was mentioned via [RenderEdge topic](https://www.hiveworkshop.com/threads/renderedge-basic-version.288375/)

>FPS is unlocked, now it can be above 64 with disabled vsync (thanks to Karaulov);

**Comment by Karaulov** [comment]
If FPS can bigger that 64. But if  40 fps with d3d9 or d3d8to9... ?

**Comment by elishacloud** [comment]
@Karaulov, I am pretty sure the issue is your graphics card.  It is over 9 years old and not able to handle as many FPS.  I tested this on my computer (GeForce GTX 780) and it runs at 60 FPS without an issue.  Check out this video [here](https://www.youtube.com/watch?v=PSaLdo8W6Ao) for details about the performance of your graphics card.

A few more comments:

1. d3d8to9 seems to already run at the same speed as native d3d9, which is pretty good.
2. After quickly looking at the the functions that are used by Warcraft III, I don't see much we can do to optimize this.
3. Researching the performance difference between dx8 and dx9, other people report dx8 as running faster than dx9.  See [here](https://www.reddit.com/r/tf2/comments/3mjstu/dx8_vs_dx9/) and [here](http://www.teamfortress.tv/32461/dx9-1-runs-better-than-dx8-1) for two examples.  It seems that dx8 runs at higher FPS while dx9 is more stable.
