### ISSUE TITLE
Cant use Driver Forced AA

### ISSUE THREAD

**Issue by LethalManBoob** [crosire/d3d8to9#54]
At least in serious sam. It worked before unless i alt tabbed. 

Now its completely useless to force driver aa in the nvidia control panel.

**Comment by crosire** [comment]
Want do you mean by "it worked before"?

**Comment by SonicFreak94** [comment]
Working fine here with Sonic Adventure DX (2004 version), albeit with an AMD card.

**Comment by LethalManBoob** [comment]
As far as im aware driver forced aa worked for all versions until 1.6.0

**Comment by elishacloud** [comment]
I am using an nVidia GTX 780 card and forcing the driver to AA works fine for me.  I tested with both Raymond 3 and Serious Sam 2.  Are you sure it is not a driver problem?  Try downloading the latest driver nVidia site and re-installing it.

Otherwise can you tell me exactly which settings you changed on nVidia and what you changed them to?

Below are the settings I used (click on it to enlarge):

![nvidia](https://user-images.githubusercontent.com/25625456/31807161-68c3d156-b521-11e7-8228-56fc3de23594.png)

**Comment by Archlogic** [comment]
Might wanna play around with Nividia Profile Inspector, too.

**Comment by LethalManBoob** [comment]
Serious Sam The first encounter and second encounter dont allow me to force aa when in d3d mode. 

Which i gotta run it in because it caps my refresh rate to 60hz in opengl mode.

**Comment by LethalManBoob** [comment]
Same issue with a game called Firestarter my gsc gameworld. Stalker guys. Its on gog.

I would also like to state that game is a can of worms with the d3d8.dll module.

It.. dosent like it. random polygon flicker garbage, missing certain objects and random ctd's.

**Comment by LethalManBoob** [comment]
postal 2 dosent work ether. (:

**Comment by elishacloud** [comment]
Firestarter is already being discussed in a different issue, see #49.

For the issue with forced AA, you did not answer the questions:

1. Are you sure it is not a driver problem? Try downloading the latest driver nVidia site and re-installing it.

2. Can you tell me exactly which settings you changed on nVidia and what you changed them to?

3. Also, can you go back and verify that it still works with [v1.5.0](https://github.com/crosire/d3d8to9/releases/download/v1.5.0/d3d8.dll) but not [v1.6.0](https://github.com/crosire/d3d8to9/releases/download/v1.6.0/d3d8.dll)?  I am wondering if some other update on your computer broke this.

4. When you say "dont allow me to force aa when in d3d mode", what do you mean?  Does the game play just without AA?  Does the game not play?  What are you seeing on the screen?  I need to better understand your issue here.

**Comment by LethalManBoob** [comment]
1. Its defiantly not driver dependent. I had older drivers but i actually
formatted in that time and updated to 388.11. Still no luck.

2. I tried forcing msaa, sgssaa, hraa eveything. Nothing works.

3. Seems no matter how far back I go it looks like driver aa wont work with
any game now. so maybe update did do somthing

4. Yes I can play as normal but simply put aa dosent work.

**Comment by LethalManBoob** [comment]
Update. I think the issue is nvidia driver related. I cant force aa in a few select games that i used to be able to.

**Comment by crosire** [comment]
Closing, since this doesn't appear to be a bug with d3d8to9.
