### ISSUE TITLE
D3DXAssembleShader can't handle D3DXASM_DEBUG flag

### ISSUE THREAD

**Issue by PatrickvL** [crosire/d3d8to9#64]
D3DXAssembleShader can't handle D3DXASM_DEBUG flag - this introduces additional comment lines, which throws off the d3d8to9 regex'es.

**Comment by elishacloud** [comment]
From what I can tell the D3DXASM_DEBUG flag is only allowed in the `D3DXAssembleShader` function and not the `D3DXDisassembleShader` function.  By the time the `D3DXAssembleShader` function has been called all the RegEx's have been completed.

I did a quick test by adding this flag to all `D3DXAssembleShader` functions in d3d8to9 and ran a few tests on some games without any issues.

I am wondering if you are sending shaders that have been pre-assembled with the D3DXASM_DEBUG flag to d3d8to9.  If so why not just wait until the shaders go to d3d8to9 and then have d3d8to9 add the debug flag?

Can you describe a little bit more what you are doing here and how I can reproduce this?

BTW: if it would help we could easily make it so that debug builds of d3d8to9 automatically set this flag.
