### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Aeirex** [crosire/d3d8to9#88]
For our game Nin Online we decided to use this since we use DirectX8 in our game engine.
https://www.ninonline.org/index.php

Right now, we're using version 1.4.0, because 1.9.1 has more white screen issues. Can you take a look into it?

**Comment by elishacloud** [comment]
The issue here is caused by this check in [5743692](https://github.com/crosire/d3d8to9/commit/57436929e7d81821b9d61feff6f29715552fccf8).  If I remark out these two lines [here](https://github.com/crosire/d3d8to9/blob/5cbd8f53d6547b16b4c274a98022da515222030f/source/d3d8to9_device.cpp#L1053) and [here](https://github.com/crosire/d3d8to9/blob/5cbd8f53d6547b16b4c274a98022da515222030f/source/d3d8to9_device.cpp#L1061) the game works fine.  So it looks like this is caused by an issue with how d3d8to9 handles palettes.

**Comment by elishacloud** [comment]
@Helladen, can you tell me how to reproduce this?  My previous testing was not valid.  I am not seeing any white screens.

**Comment by Helladen** [comment]
It only happens to some people who have installed Direct X9. I don't know how to reproduce it.
