### ISSUE TITLE
Add information about VC 2015 runtime requirement

### ISSUE THREAD

**Issue by JarnoVgr** [crosire/d3d8to9#89]
Had troubles with d3d8to9 on a new PC due to VC 2015 runtime not being installed. It would be great if that requirement could be added to the `README.md`.

**Comment by CookiePLMonster** [comment]
Or just compile with /MT so no runtimes are needed.

**Comment by JarnoVgr** [comment]
I've taken the build from the releases page, and thus didn't compile it myself.

**Comment by crosire** [comment]
There isn't a requirement per se. Just the builds that are created via AppVeyor happen to be build with VC2015, so that particular version is required. Technically could also be 2017 or any other version. So not something that really belongs into the README, which is about the project itself, not the build output published on the release page.
