### ISSUE TITLE
Optional Direct3D9Ex mode

### ISSUE THREAD

**Issue by CookiePLMonster** [crosire/d3d8to9#9]
Do you reckon implementing this as an opt-in feature could have any advantages other than screenshoting not being broken with DWM?

The removal of managed pool could possibly be the trickiest part.

**Comment by crosire** [comment]
D3D9Ex is mainly beneficial for windowed applications, which is rare among D3D8 games, so I doubt it's worth the hassle.

**Comment by CookiePLMonster** [comment]
Maybe no device lost on Alt-Tab for some games which can't minimize?

**Comment by CookiePLMonster** [comment]
Given the fact no one managed to list any benefits from d3d9ex (including myself), it's probably not worth the hassle ;)

**Comment by CookiePLMonster** [comment]
Given the fact no one managed to list any benefits from d3d9ex (including myself), it's probably not worth the hassle ;)

**Comment by cher-nov** [comment]
@crosire
> which is rare among D3D8 games
It's not rare at all. The simplest and most obvious example is the vast majority of games made on the classic GameMaker engine before version 8.1 (after which it turned into Studio). They *all* used DirectX 8.1 and worked in windowed mode by default, while full-screen was not exclusive.

**Comment by CanerKaraca23** [comment]
@CookiePLMonster Hi, can you consider to reopen this issue? Using d3d9ex instead of d3d9 will be good i think. @crosire 

**Key Benefits of D3D9Ex**

- **Instant and Safe Alt-Tabbing:** Eliminates the "Device Lost" error. Tabbing out and back into the game is seamless and instant, preventing the game from freezing, crashing, or forcing textures to reload.
- **Optimized RAM Management:** Unlike D3D9, D3D9Ex does not duplicate video memory (VRAM) data into the system memory (RAM). This significantly reduces overall RAM usage.
- **Reduced CPU Overhead:** It communicates more efficiently with modern Windows Display Driver Models (WDDM), lowering the processing strain on your CPU and reducing micro-stutters.
- **Enhanced Stability with Mods:** The improved memory allocation prevents "Out of Memory" crashes, which is highly beneficial if you are running heavy graphics mods, HD texture packs, or ENBs.
- **Better Modern OS Compatibility:** It integrates natively with Windows 10 and Windows 11, offering a much more stable and smoother frametime pacing compared to the legacy D3D9 runtime.

**Comment by elishacloud** [comment]
@CanerKaraca23, I added an option to convert d3d9 to d3d9Ex in my [dxwrapper](https://github.com/elishacloud/dxwrapper/) project.  It also includes the latest d3d8to9 build.  You can use that for this case.

**Comment by CanerKaraca23** [comment]
> [@CanerKaraca23](https://github.com/CanerKaraca23), I added an option to convert d3d9 to d3d9Ex in my [dxwrapper](https://github.com/elishacloud/dxwrapper/) project. It also includes the latest d3d8to9 build. You can use that for this case.

Thanks, but there is a problem when i use dxwrapper. EAX is not working anymore on Vice City. It's fine with D3d8to9. Here is log: 
[dxwrapper-gta-vc.log](https://github.com/user-attachments/files/30158737/dxwrapper-gta-vc.log)

Also i have question, is it possible to combine D3d8to9 and D3d9on12 and run d3d8 games on d3d12? I tried in Vice city but game didn't launched.

**Comment by elishacloud** [comment]
> Thanks, but there is a problem when i use dxwrapper. EAX is not working anymore on Vice City. It's fine with D3d8to9.

Yes.  d3d9Ex doesn't work the same as d3d9 and not all cases work perfectly yet.  I did put a few recent fixes in, you could try the latest build under the Actions tab.  Otherwise, I will just need to enhance it more as I have time.

> Also i have question, is it possible to combine D3d8to9 and D3d9on12 and run d3d8 games on d3d12?

Yes, that works.  However, keep in mind that D3d9on12 was written by Microsoft not me.  So I have no control of issues with that.  See here:  https://github.com/microsoft/D3D9On12

**Comment by CanerKaraca23** [comment]
> 
> Yes. d3d9Ex doesn't work the same as d3d9 and not all cases work perfectly yet. I did put a few recent fixes in, you could try the latest build under the Actions tab. Otherwise, I will just need to enhance it more as I have time.
> 

I am using latest action build and it's still same with d3d9 only. d3d9Ex doesn't matter. EAX broken and not working.

> 
> Yes, that works. However, keep in mind that D3d9on12 was written by Microsoft not me. So I have no control of issues with that. See here: https://github.com/microsoft/D3D9On12

No luck with Vice City unfortunately. But it would be interesting to run VC on d3d12.

Thanks for answers, but it's going off-topic.
